name: 'shell'
description: |
  创建一个script
  create a shell request

author: lee-cq
branding:
  icon: 'terminal'
  color: 'blue'

runs:
  using: 'node16'
  pre: 'index.js'
  main: 'index.js'
  post: 'index.js'
