name: test Shell

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  test_shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/shell
        with:
          hostname: ${{ github.event.inputs.hostname }}
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
          jumpserver_host: ${{secrets.JUMPSERVER_HOST}}
          jumpserver_ptoken: ${{secrets.JUMPSERVER_PTOKEN}}
          shell_username: ${{secrets.SHELL_USERNAME}}
          shell_password: ${{secrets.SHELL_PASSWORD}}
